color: null
fieldLayouts:
  07a451ed-5806-4ef4-94a3-e5bb0c55fe8d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d4b7a59c-9d4f-4ac8-a4a3-2f63ce38d4bb
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 582be10c-d53c-4101-b2a3-d7ce716969a3 # Module
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4dc5f1f3-7b21-4da2-9b3e-693a8a3efc4f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 782ea26b-6099-41c0-a9d0-c0b9b5666c07
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ba55e41d-744e-4c1a-8f89-9b8469a2e163 # SEO-Titel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69bd299b-f9fd-4e34-9b96-fea266bee329
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62533532-ce6a-420e-8c67-b7c8029c525e # SEO-Beschreibung
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6281855c-b87c-460a-971d-939659c42cad
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ff673cc2-1bbc-4d7d-9f06-ccfbf36b33b5 # Indexierung
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3913d7a-e400-491d-806b-69fdaa0f0ca1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 186d67c0-9ba8-424d-acd7-ed6dd42c79a5 # Priorität
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fe92bb2-2648-4ddf-81fc-ade6dabd01a6
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: f879647d-6ef4-439c-98b5-b7ccfcd937f0
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 29181b3d-4dd0-4ddf-bf2f-c0f11d0df767 # Stage Skyline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5e235381-5b6c-45ac-a2de-df83a6eea9b0
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8fcea34e-570d-4161-a67c-7f02e0c3c3a0 # Stage Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 209f5fb7-d75a-42c3-aaac-f1b16f977750
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7edacf73-0358-4f0e-a9c8-687eb26db450 # Stage Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46be764e-40d2-488e-b01c-e946502b0bee
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 991c3fc7-9fbd-41bc-bb0c-7f9330eef165 # Stage Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10b51195-c9fc-44ae-acab-25a9ba2cc06a
            userCondition: null
            warning: null
            width: 100
        name: Stage
        uid: f1de11ce-76ee-4038-abe5-16b12e9e750a
        userCondition: null
handle: blog
hasTitleField: true
icon: ''
name: Blog
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
