color: lime
fieldLayouts:
  64715379-842f-4a1e-b735-91561c600c07:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9144f374-ad02-403b-bda5-0f2db200cb7f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 6ba183da-ef91-4615-850d-4b82daf96849 # Link
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7ed95d0b-8441-473c-aad0-94c97a038bd0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: fce65c53-9b75-47f5-a590-4413f403683a
        userCondition: null
handle: footerNavigation
hasTitleField: true
icon: shoe-prints
name: 'Footer Navigation'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
