color: sky
fieldLayouts:
  5b8f3195-b522-483e-82ff-3f1cf7d4d202:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 674afb5b-5d71-4156-89e9-591a6dea608b
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 582be10c-d53c-4101-b2a3-d7ce716969a3 # Module
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cd64df4e-ded0-4778-bf36-b072b11cde1a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 6048aae7-9541-458e-88ab-7d23fb192437
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ba55e41d-744e-4c1a-8f89-9b8469a2e163 # SEO-Titel
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ff0a2df3-fde3-4c2e-a13c-f8eb0143090c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62533532-ce6a-420e-8c67-b7c8029c525e # SEO-Beschreibung
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 22625286-439f-4f6b-b2c9-a75d439572e5
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ff673cc2-1bbc-4d7d-9f06-ccfbf36b33b5 # Indexierung
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 012b25c6-158a-4290-97d1-734c639277f8
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 186d67c0-9ba8-424d-acd7-ed6dd42c79a5 # Priorität
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f16c46f-52ce-4791-98ef-9b84aede1225
            userCondition: null
            warning: null
            width: 100
        name: Seo
        uid: 5b149739-d41d-44c5-9ded-ef9596462637
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 29181b3d-4dd0-4ddf-bf2f-c0f11d0df767 # Stage Skyline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24939541-900b-4ec0-bfd9-0f91befa14bf
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8fcea34e-570d-4161-a67c-7f02e0c3c3a0 # Stage Headline
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3b87454e-d82b-4b35-b33c-b935069fa027
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 7edacf73-0358-4f0e-a9c8-687eb26db450 # Stage Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a567c69d-563f-4aec-8571-749ad2bde2af
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 991c3fc7-9fbd-41bc-bb0c-7f9330eef165 # Stage Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f74534ce-dffc-4684-bb22-6e3be14b6a99
            userCondition: null
            warning: null
            width: 100
        name: Stage
        uid: 6d4a9a34-d5bb-4231-af8b-a58f81271887
        userCondition: null
handle: project
hasTitleField: true
icon: rectangle-history
name: Project
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
