childBlocks:
  - accordionItem
color: null
conditions: null
description: ''
enabled: true
field: 582be10c-d53c-4101-b2a3-d7ce716969a3 # Module
group: null
groupChildBlockTypes: true
handle: accordion
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 1
minSiblingBlocks: 0
name: Accordion
topLevel: true
