childBlocks: null
color: null
conditions: null
description: ''
enabled: true
field: 582be10c-d53c-4101-b2a3-d7ce716969a3 # Module
fieldLayouts:
  04c83f9b-ff74-4999-8ab2-11dc7ac316e0:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-19T21:37:59+00:00'
            elementCondition: null
            fieldUid: b40ec017-c91e-4689-b32c-0ba8fda3a466 # Text Editor
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 99b16d4b-62df-455f-b848-f2dbff38440b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: c8d14482-0593-4fae-a9a3-af63f1f45b57
        userCondition: null
group: null
groupChildBlockTypes: true
handle: code
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Code
topLevel: true
