childBlocks: null
color: null
conditions: null
description: ''
enabled: true
field: 582be10c-d53c-4101-b2a3-d7ce716969a3 # Module
fieldLayouts:
  87fd98fe-890d-4b46-8d58-6e857573df31:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-19T21:36:59+00:00'
            elementCondition: null
            fieldUid: fdd12ccd-4b08-42bb-9a6b-298784bf9343 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 312639e3-f0ba-4b12-9208-d889edec92d8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 0cd38759-26d6-4985-877a-e42925b9e2c4
        userCondition: null
group: null
groupChildBlockTypes: true
handle: image
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Image
topLevel: true
