childBlocks: null
color: green
conditions: null
description: ''
enabled: true
field: 582be10c-d53c-4101-b2a3-d7ce716969a3 # Module
fieldLayouts:
  8eb88863-bd86-4116-a464-740f129dbbe5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2024-12-19T21:36:59+00:00'
            elementCondition: null
            fieldUid: e43fa49e-981e-4db6-90e4-b05806a84e06 # Text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 08ebda49-dc23-4aec-b18f-10ad9b7b5efe
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-12-23T20:47:05+00:00'
            elementCondition: null
            fieldUid: fdd12ccd-4b08-42bb-9a6b-298784bf9343 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4e56a887-f2d0-4f9d-99b3-7dc88699d419
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4749c363-f493-4f7d-806d-b526b9f2a561
        userCondition: null
group: null
groupChildBlockTypes: true
handle: parallax
icon: null
iconFilename: ''
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Parallax
topLevel: true
