columnSuffix: null
handle: entryType
instructions: null
name: Eintragstyp
searchable: false
settings:
  options:
    -
      __assoc__:
        -
          - label
          - News
        -
          - value
          - news
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Blogs
        -
          - value
          - blog
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Projects
        -
          - value
          - project
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
