dateModified: 1734986825
email:
  fromEmail: $EMAIL_SENDER_ADDRESS
  fromName: $EMAIL_SENDER_NAME
  replyToEmail: null
  template: ''
  transportSettings:
    host: $EMAIL_HOSTNAME
    password: $EMAIL_AUTH_PASSWORD
    port: $EMAIL_PORT
    useAuthentication: $EMAIL_USE_AUTH
    username: $EMAIL_AUTH_USERNAME
  transportType: craft\mail\transportadapters\Smtp
fs:
  global:
    hasUrls: true
    name: Global
    settings:
      path: '@assetsRootPath/global'
    type: craft\fs\Local
    url: '@assetsBaseUrl/global'
meta:
  __names__:
    0d60f280-15cb-4a7f-a9f9-925cff9353ef: Page # Page
    1b7fd4c0-889b-4a8c-8010-e7915547311d: 'Datei Link' # Datei Link
    2be93fc8-a8c8-4ef9-a881-6999042291c9: Kontaktformular # Kontaktformular
    2cd290cd-8f1d-486c-b6cf-5d12ecc3cd2d: Intern # Intern
    4b3997e5-1b4b-41a8-be6e-6a2214024368: Zahl # Zahl
    5ec4cdda-2b82-4458-9037-61b4ded6e999: 'Public Schema' # Public Schema
    5fe8711f-ea1c-4f7c-8b17-551c22911836: E-Mail # E-Mail
    6ba183da-ef91-4615-850d-4b82daf96849: Link # Link
    6fc95d6d-5f0d-47db-9505-2dcfa358def6: 'Textabschnitt - Absatz - Text' # Textabschnitt - Absatz - Text
    7a5156f8-29e4-40da-9574-4f2b8abdff1e: Hauptnavigation # Hauptnavigation
    07c5f08c-88c4-4799-9bd6-e98816f41036: Homepage # Homepage
    7edacf73-0358-4f0e-a9c8-687eb26db450: 'Stage Description' # Stage Description
    7f21cde3-04cd-4ccd-ab93-17ac442663b7: Spalten # Spalten
    08ad0a02-3b3d-4515-8dd5-de9434d163a5: Inaktiv # Inaktiv
    8ce1d03e-0859-41ca-b33e-1ed4a3153659: Code # Code
    8fcea34e-570d-4161-a67c-7f02e0c3c3a0: 'Stage Headline' # Stage Headline
    9fdf44e3-df83-45d2-8b7a-2398e417e976: Gruppe # Gruppe
    19bf9376-e0d8-4564-bc04-dc45b56cd87a: 'Blog Type' # Blog Type
    28c19881-a5ea-4055-abaa-4adcd6e7cd3c: Textabschnitt # Textabschnitt
    42b295ab-e778-4c44-87d7-ad7aa073f4d3: Linktext # Linktext
    67a6fc2c-6cec-4678-940f-945e6d696813: Eintragstyp # Eintragstyp
    71a5cbef-8243-4197-bd56-d70c92ef4e48: 'Footer Navigation' # Footer Navigation
    77e2762e-83e2-424b-818a-01034ad4996d: 'Footer Navigation' # Footer Navigation
    82ec8175-c042-421f-99cd-929ce4f61f95: Headline # Headline
    92f3cc18-4537-499a-bbbb-0576d2982d86: Extern # Extern
    186d67c0-9ba8-424d-acd7-ed6dd42c79a5: Priorität # Priorität
    270f9ad4-9d7d-43f3-a1c4-19ac167afc24: 'Category color' # Category color
    302ddeb7-0ec9-48ed-91da-7efc4552c901: Blogs # Blogs
    529ac1bc-4fd6-4508-b075-8c7b1cee7a63: Icon # Icon
    582be10c-d53c-4101-b2a3-d7ce716969a3: Module # Module
    659e06e8-6fe9-430b-a30d-6b02f7409190: Spalten # Spalten
    954edfab-2362-42ed-8269-00a88d878aa7: Global # Global
    991c3fc7-9fbd-41bc-bb0c-7f9330eef165: 'Stage Image' # Stage Image
    3523d483-f376-4e39-9361-5223a1a2e5d2: Parallax # Parallax
    12853f5e-57c7-40e4-908a-b7be4ce30bc7: Default # Default
    29181b3d-4dd0-4ddf-bf2f-c0f11d0df767: 'Stage Skyline' # Stage Skyline
    64259d2d-817e-4fb4-a9be-619bd3c57014: Aktiv # Aktiv
    4588913f-bc97-4ebe-8ec3-29a8efce9e67: Bilder # Bilder
    9150003f-ee06-497a-bceb-c2c169d93206: sara # sara
    62533532-ce6a-420e-8c67-b7c8029c525e: SEO-Beschreibung # SEO-Beschreibung
    a029f576-c04e-4755-8637-52c45e991860: Image # Image
    a5ba3d2a-68ae-4b35-a7bf-f9ef56ec8d9c: Seiten # Seiten
    a7f070a5-b268-4ce3-9efa-a924ef697dc4: Seitenkonfiguration # Seitenkonfiguration
    a209f7b5-77be-4311-b663-5d1abe0a0df2: 'Blog type' # Blog type
    a807a09e-c6e8-4d37-974d-6ef3c2632920: Boilerplate # Boilerplate
    a861ea85-4c1a-458e-bc22-edfa3741c096: 'Einträge (Liste)' # Einträge (Liste)
    ac98e4ce-ad0c-4032-88e2-e57f1291e6ff: Text # Text
    aecd756d-ec71-4ae9-b7ce-d66b5cf54270: Projects # Projects
    afcaedf5-aa35-4d4e-a7ad-e1be2bfb90d4: 'Headline level' # Headline level
    b40ec017-c91e-4689-b32c-0ba8fda3a466: 'Text Editor' # Text Editor
    b318a2f1-bca0-4969-b6ee-07239f330ead: 'Private Schema' # Private Schema
    b480ae0c-6e29-4217-8d7f-9a9834d56c73: Absatz # Absatz
    ba55e41d-744e-4c1a-8f89-9b8469a2e163: SEO-Titel # SEO-Titel
    ba451899-838d-4daf-b104-8389289f840a: Überschrift # Überschrift
    c4ddcf89-46f3-47b0-b0a6-ff5cd3337933: Link # Link
    c8f1bdc6-8e91-4fd3-83e5-f96a507bb27c: 'Link Layout' # Link Layout
    cd715ebe-ed8a-469b-8c5e-03da82ba7be0: 'Background color' # Background color
    cef3b054-1482-48de-9abb-d63fb3ee178e: 'Alt Text' # Alt Text
    d632eb1b-e6c2-4db4-8bdd-a6ca9d7b6243: Hauptnavigation # Hauptnavigation
    df9d502e-e0d0-4608-bc4b-73ea824cf9e3: Breite # Breite
    e43fa49e-981e-4db6-90e4-b05806a84e06: Text # Text
    f57ff8c0-9c9b-43de-bc3e-5fe45d72f6bd: Project # Project
    f793a6da-d9c1-4133-8a8e-bed308d30ca5: Blog # Blog
    fdd12ccd-4b08-42bb-9a6b-298784bf9343: Image # Image
    ff673cc2-1bbc-4d7d-9f06-ccfbf36b33b5: Indexierung # Indexierung
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  int-contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  int-craft-backup-service:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      backup_interval: '30'
      ftp_host: w01051ae.kasserver.com
      ftp_pass: R4MUhAhgxYEusa2F
      ftp_port: ''
      ftp_upload_path: backups/boilerplate-test/
      ftp_user: f010d2f9
      task_runner_passkey: rvjotndnjosfwsqmrmmqukvshldjwsqq
      task_runner_url: 'https://sara.ddev.site/actions/int-craft-backup-service/backup/run-task/?passkey=rvjotndnjosfwsqmrmmqukvshldjwsqq'
  int-graphql-extended:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  neo:
    edition: standard
    enabled: true
    licenseKey: NLJSR31FY5EDQWGNH5RAQRTJ
    schemaVersion: 5.0.0.1
system:
  edition: pro
  live: true
  name: Boilerplate
  retryDuration: null
  schemaVersion: 5.5.0.0
  timeZone: Europe/Berlin
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
