defaultPlacement: end
enableVersioning: true
entryTypes:
  - f57ff8c0-9c9b-43de-bc3e-5fe45d72f6bd # Project
handle: projects
maxAuthors: 1
name: Projects
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  9150003f-ee06-497a-bceb-c2c169d93206: # sara
    enabledByDefault: true
    hasUrls: true
    template: projects/_entry
    uriFormat: 'projects/{slug}'
type: channel
